apiVersion: v1
kind: Secret
metadata:
  name: yelp-camp-secrets
type: Opaque
data:
  CLOUDINARY_CLOUD_NAME: ZGN2aGdseWl0
  CLOUDINARY_KEY: NTI1MTY1ODk3MjE0Mzk5
  CLOUDINARY_SECRET: NGNGZkJpVFhCcU14ZXZzMktwRGxsaUo5STJj
  MAPBOX_TOKEN: cGsuZXlKMUlqb2laR2wyZVdGbmIzSmhiblJzWVRFM01EZ2lMQ0poSWpvaVkyMXVlWEl4Wmpnek1ETjFZVEp5YzJWbGJqbHRNMnRwTXlKOS42a251RWMxS0NlMTdNLXF1Yy1kemp3
  DB_URL: bW9uZ29kYitzcnY6Ly9hZG1pbjphZG1pbjExMjJAY2x1c3RlcjAueXN2Y2Z4dy5tb25nb2RiLm5ldC8/YXBwTmFtZT1DbHVzdGVyMA==
